version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: local-mongodb
    ports:
      - "27017:27017"
    environment:
          MONGO_INITDB_ROOT_USERNAME: user_name
          MONGO_INITDB_ROOT_PASSWORD: password
